name: Android CI

on:
  push:
    branches:
      - main

  #Allow the user to manually start this workflow on actions tab
  workflow_dispatch:

  #A workflow run is  made up one or more jobs that run sequentially or in parallel
  jobs:
    build:
      runs-on: ubuntu-latest
      steps:
        - name: Checkout the code
          uses: actions/checkout@v2

        - name: Setup JDK
          uses: actions/setup-java@.4.2
          with: java-version:1.8

        - name: Build with Gradle
          run: ./gradlew build

        - name: Upload APK file
          uses: actions/upload-arifact@2.1.4
          with:
            name: app
              path: app/build/outputs/apk/debug/app-debug.apk




